### ISSUE TITLE
Connection issues when Application is open

### ISSUE THREAD

**Issue by ExtinctDragonOG** [ShinjiruApp/Shinjiru#14]
I've been using Shinjiru for a couple days, worked great. Since yesterday I noticed I was having Internet problems, typical troubleshooting ensued and I realized it was something with my PC. I gave up until today when I finally figured out what it was, when Shinjiru is open every couple seconds I lose connection for about one second. I'm not sure if other people are getting the same problem as I am but when it's closed I no longer get connections issues. I tried reinstalling but that didn't help, screenshot included is what it looks like when I ping google.com with it open. I also noticed that along with the connection problems it started picking random anime from my list that I was watching. Thanks for any help :)
![cmd_2018-07-06_14-18-35](https://user-images.githubusercontent.com/40926038/42415756-ca2657ce-8227-11e8-87e5-913ce23b2ce7.png)

**Comment by Kazakuri** [comment]
Huh, that's really strange...

When it was picking random anime from your list that you were watching, were any of the [supported programs](https://github.com/ShinjiruApp/Shinjiru/blob/77ca7e91fcea459b7f9d69b3352f0de5fc495aec/res/mediaPlayers.json) running?

If you can upload a `Shinjiru.log` file from when the issue was going on that'd be really helpful.

**Comment by ExtinctDragonOG** [comment]
Where would I find the log file? Yeah, I use VLC and it worked perfectly fine before.

**Comment by Kazakuri** [comment]
It'd be in the Shinjiru installation folder. Probably `C:/Program Files/Shinjiru/Shinjiru/Shinjiru.log`

So when VLC was open and playing it was changing to a random anime being detected?

**Comment by ExtinctDragonOG** [comment]
Usually yeah but I just tested it, it seems to be different per anime. Nichijou worked fine but Steins;Gate 0 and Noragami would give the wrong anime.
[Shinjiru.log](https://github.com/ShinjiruApp/Shinjiru/files/2181290/Shinjiru.log)

**Comment by Kazakuri** [comment]
Does the connection issue only happen when you're watching an anime? The frequency that it's happening makes it seem like something's going wrong with the recognition.

That log doesn't contain much though, did you try running VLC to demonstrate the issue before uploading that log file? The log file is re-created after every run of the program

**Comment by ExtinctDragonOG** [comment]
No, it happens even if I'm not watching anything and Yeah I was running VLC and just switching between anime, it didn't update past that.

**Comment by Kazakuri** [comment]
Huh, that's really weird. If you turn off anime recognition the issue stops though, right?

I can't recreate Noragami or Steins;Gate 0 being misrecognized at all, can you get an example of a filename that causes the issue as well as the anime that it gets recognized as instead?

**Comment by ExtinctDragonOG** [comment]
No, it still does the same thing with recognition off. The way I have it setup is, a folder with the anime name and each video file is titled "Episode (insert episode here)" ex. Episode 1. Now what I just figured out is if lets say I name the video file Noragami Episode 1 it detects it but if it's just "Episode 1" it gives a false positive. Right now it's detecting it as Re:Creators, and it doesn't matter what anime it is, I tried loading up a Steins;Gate 0 episode and it also detects as Re:Creators, it gets the episode right just not the anime. Also for some reason, Nichijou works fine but others it doesn't, the file and folder names are the same format. Earlier it was detecting it as Planetes and Nisekoi. Closing and reopening the app gives a different anime, this time it was Tokyo Ghoul VA when running Steins;Gate 0 and just the original Tokyo Ghoul when loading up Noragami which is super weird.

**Comment by Kazakuri** [comment]
I have no idea what would be causing that at all. The only thing that runs on a short loop (5 seconds) is the media recognition code.

Ah okay, I can recreate it like that. Essentially what's happening is that VLC provides `Episode 3.mkv - VLC Media Player` to Shinjiru and Anitomy will parse that as episode 3 of a show called "" (an empty string). That becomes an issue because when Shinjiru adds synonyms to series, it adds in the English, Romaji, and Native titles in as synonyms since we only display one of the three elsewhere. A ton of shows don't actually provide English titles because they're either equivalent to the Romaji one or they're just not officially licensed, so a blank string does get added to the synonym list.

I'll exclude empty strings so they won't get randomly selected from title lookups but that wouldn't make it so the right show is detected either. Taking the file path into consideration is a lot more work to do each recognition check (reading file handles instead of enumerating windows is expensive) and it'd most likely cause other recognition issues along the road so I'm afraid there isn't really anything I can do to get it to recognize them properly.

**Comment by ExtinctDragonOG** [comment]
I see what you mean, I don't really have a problem with fixing the file names and such, and the internet problems isn't THAT much of a problem because it's only when its open, as long as I close it after I'm finished using it, its fine. I will keep troubleshooting around with Shinjiru to see if anything works. Will update if I find anything :)

**Comment by ExtinctDragonOG** [comment]
Things I've tried: Turning off Windows Defender and Firewall, updating windows, closing most programs that are running, using a different version (3.2.0), running as admin and compatibility mode, and running from the zip file. Still nothing, I really don't have a clue, I will probably wait for an update for Shinjiru to come out and see if it magically fixes itself. Thanks for the help though :)
