### ISSUE TITLE
Episode increment of a "Repeating" anime puts it to "Watching"

### ISSUE THREAD

**Issue by ohyou** [ShinjiruApp/Shinjiru#33]
Windows 10, app version 3.3.3.

1. Put any anime into the "Rewatching" cateogiry on Anilist
2. Verify that the said anime is in the "Repeating" tab in Shinjiru
3. Watch an episode of said anime while Shinjiru is opened
4. Observe the said anime being moved into the "Watching" category, both in the app and on the website

Expected behavior: the anime in question remains in the "Rewatching" category after the update.

**Comment by Kazakuri** [comment]
Oops, sorry about that. Shinjiru automatically moves the series to watching / completed based on the episode being watched so that users don't have to worry about it being in planning, dropped, or paused unintentionally, but I forgot to make rewatching be maintained.

I'll release a version tomorrow with the fix deployed.
