### ISSUE TITLE
Video titles with underscores instead of spaces aren't properly recognized

### ISSUE THREAD

**Issue by ohyou** [ShinjiruApp/Shinjiru#36]
-  A file name that gets recognized correctly:
`[Some-Stuffs] Jojo's Bizarre Adventure Diamond is Unbreakable 02 (1920x1080 Blu-Ray FLAC) [6DC2C5B8].mkv`
- A file name that gets recognized incorrectly:
`[Some-Stuffs]_Jojo's_Bizarre_Adventure_Diamond_is_Unbreakable_02_(1920x1080_Blu-Ray_FLAC)_[6DC2C5B8].mkv`

It's fairly common to replace spaces with underscores or dashes, so I think that this is an unintended behavior.

**Comment by Kazakuri** [comment]
Most of the time it shouldn't be an issue but that example is a bit of a tricky case. 
Title matching considers edit distance when matching titles, since a lot of the time special characters have some sort of meaning in the titles (For example `New Game!` vs `New Game!!`)

In the case of `Jojo's_Bizarre_Adventure_Diamond_is_Unbreakable`, it ends up being an edit distance of 6 (5 underscores and the colon missing after `Adventure`), and gets thrown out as a possibility since going past 5 changes usually causes more false positives than anything.

Though I can't actually name a series that uses underscores in the title and they are incredibly common in filenames over spaces so it does make sense to toss them before even trying to match to a title.
I'm a bit hesitant to replace dashes though, since they're a lot more common in anime titles than underscore are.

I'll try to get a new release out tomorrow with that change made, but there are a few other fixes that I want to get committed first too. Thanks!
