### ISSUE TITLE
Shinjiru Installer doesn't create start menu shortcut

### ISSUE THREAD

**Issue by Melvinkooi** [ShinjiruApp/Shinjiru#4]
I've quickly tried to use the installer of the new Shinjiru version (3.0.0 release) and i see it doesn't create a Shinjiru shortcut in it's folder on the start menu. I only see the uninstaller there in the folder.

I'm not sure if the installer conflicts with the portable installation, which i have on a separate disk on my computer.

**Comment by Kazakuri** [comment]
Woops, fixed in dfe0cac!
Since it's not an actual change to Shinjiru I'm not going to do a release for it, but I have updated the installer in the current release.

Both the installer and plain zip versions use all the same registry keys and user setting directories so it's not quite a truly portable version.
